name: Force CRLF for files inside the Git index

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  enforce-crlf:
    runs-on: ubuntu-latest
    steps:
    - name: Enforce CRLF action
      uses: DecimalTurn/Enforce-CRLF@ec751ecfeb0e0cf51d19f295435c7a6ec10bac15 #v1.1.3
      with:
        extensions: .bas, .frm, .cls, .ctl, .dsr, .dob, .pag, .vbg, .vbl, .vbp, .vbr, .vbw
        do-checkout: true
        do-push: true
